version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_URL=postgresql+asyncpg://postgres:123456@postgres:5432/contacts_app

volumes:
  postgres-data: 